app/blueprints/auth.py
import os
import secrets
import requests

from validators import url as validate_url
from time import ctime, time
from urllib.parse import urlencode
from dotenv import load_dotenv
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import and_
from flask_login import login_user, logout_user, login_required, current_user
from flask import Blueprint, redirect, url_for, render_template, flash, abort, \
    session, current_app, request

from app import db
from app import login
from app import logs
from app.models.database import Users
from app.models.database import Groups
from app.helpers.modpipe import get_form_data

auth = Blueprint('auth', __name__)

@login.user_loader
def load_user(id):
    return db.session.get(Users, int(id))

@auth.route('/')
def index():
    return render_template('login.html')


@auth.route('/logout')
def logout():
    logout_user()
    flash('You have been logged out.')
    return redirect(url_for('modpipe.index').replace('http://','https://'))

@auth.route('/authorize/<provider>')
def oauth2_authorize(provider):
    if not current_user.is_anonymous:
        return redirect(url_for('auth.index').replace('http://','https://'))
    provider_data = current_app.config['OAUTH2_PROVIDERS'].get(provider)
    logs.info(f"##### OAUTH2_PROVIDERS['twitch'] #####: {current_app.config['OAUTH2_PROVIDERS'].get('twitch')}")
    if provider_data is None:
        abort(404)

    # Generate a random string for the state parameter
    session['oauth2_state'] = secrets.token_urlsafe(16)

    # Create a query string with all the OAuth2 parameters
    qs = urlencode({
        'client_id': provider_data['client_id'],
        'redirect_uri': url_for('auth.oauth2_callback', provider=provider, _external=True).replace('http://','https://'),
        'response_type': 'code',
        'scope': ' '.join(provider_data['scopes']),
        'state': session['oauth2_state'],
    })
    authorize_url = provider_data['authorize_url'] + '?' + qs
    logs.info(f"##### authorize_url #####:{authorize_url}")

    return redirect(authorize_url)

@auth.route('/callback/<provider>')
def oauth2_callback(provider, new_user=False,):
    if not current_user.is_anonymous:
        return redirect(url_for('auth.index').replace('http://','https://'))
    logs.info(f"##### REQUEST #####: {request}")
    provider_data = current_app.config['OAUTH2_PROVIDERS'].get(provider)
    logs.debug(f"##### PROVIDER_DATA #####: {provider_data}")
    if provider_data is None:
        abort(404)
    
    # If there was an authentication error, flash the error messages and exit
    if 'error' in request.args:
        for k, v in requests.args.items():
            if k.startswith('error'):
                logs.info(f'{k}: {v}')
                flash(f'{k}: {v}')
        return redirect(url_for('auth.index').replace('http://','https://'))
    
    # Make sure the state parameter matches the one we created
    if request.args['state'] != session.get('oauth2_state'):
        logs.info('##### ERROR #####: State Incorrect ###')
        abort(401)
    
    # Make sure the authorization code is present
    if 'code' not in request.args:
        logs.info(f"##### ERROR #####: Authorization Code is NOT PRESENT ###")
        logs.info(f"{request}")
        abort(401)

    # Exchange the authorization code for an access token
    response_data={
        'client_id': provider_data['client_id'],
        'client_secret': provider_data['client_secret'],
        'code': request.args['code'],
        'grant_type': 'authorization_code',
        'redirect_uri': url_for('auth.oauth2_callback', provider=provider, _external=True).replace('http://','https://'),
        }
    response_url = provider_data['token_url']
    response = requests.post(response_url, response_data ,
        headers={'Accept': 'application/json'}
    )
    logs.info(f"##### response #####: {response_url}: {response_data}")
    if response.status_code != 200:
        abort(401)
    oauth2_token = response.json().get('access_token')
    if not oauth2_token:
        abort(401)
    
    # Use the access token to get the user's email address
    headers = {
            'Authorization': 'Bearer ' +oauth2_token,
            'Accept': 'application/json',
        }
    if provider == "twitch":
        headers = {
            'Authorization': 'Bearer ' +oauth2_token,
            'Accept': 'application/json',
            'Client-Id': provider_data['client_id'],
        }
    response = requests.get(provider_data['userinfo']['url'], headers=headers)
    if response.status_code != 200:
        logs.info(f"##### JSON Response #####: {response.json()}")
        abort(401)
    json_response = response.json()
    logs.info(f"##### JSON Response #####: {json_response}")
    email = provider_data['userinfo']['email'](json_response)
    oauth_id = provider_data['userinfo']['id'](json_response)
    username = provider_data['userinfo']['username'](json_response)
    display = provider_data['userinfo']['display'](json_response)
    avatar = provider_data['userinfo']['avatar'](json_response)

    logs.debug(f"##### email #####:\n {email}")
    logs.debug(f"##### Users #####:\n {Users}")

    # Find or create the user in the database
    user = db.session.scalar(db.select(Users).where(and_(Users.email == email,Users.provider == provider)))
    if user is None:
        new_user = True
        user = Users(email=email,
                     provider=provider,
                     oauth_id=oauth_id,
                     username=username,
                     display=display,
                     avatar=avatar,
                     bio=""
                )
    user.last_used = int(time())
    db.session.add(user)
    db.session.commit()

    # Log the user in
    login_user(user)
    # Make sure the user's default groups have been created
    create_user_groups = True if Groups.query.filter_by(owner=current_user.id).first() is None else False
    if create_user_groups:
        logs.info(f"Creating default groups for {current_user.display}")
        for name in ['Owner','Moderator','VIP','Everyone']:
            new_group = Groups(owner=current_user.id,name=name)
            db.session.add(new_group)
            db.session.commit()

    # Onboard User and allow them to edit their profile
    user = db.session.scalar(db.select(Users).where(and_(Users.email == email),Users.provider == provider))
    if new_user:
        return render_template('onboarding.html',user=user)
    else:
        return redirect(url_for('modpipe.dashboard').replace('http://','https://'))


@auth.route('/user')
@login_required
def view_user():
    return render_template('user.html')

@auth.route('/user/edit', methods=['GET'])
@login_required
def edit_user():
    user = db.session.scalar(db.select(Users).where(and_(Users.id == current_user.id,Users.provider == current_user.provider)))
    return render_template('user_form.html', user=user)

@auth.route('/user/update', methods=['POST'])
@login_required
def edit_user_POST():
    fields = ['type','id','groups','username','email','admin','display','avatar','bio', 'onboarding']
    form_data = get_form_data(fields)

    user = db.session.scalar(db.select(Users).where(and_(Users.id == current_user.id,Users.provider == current_user.provider)))
    display_change_date = int(time()) - 2592000
    user.username = f"""{form_data['username']}"""
    user.display = f"""{form_data['display']}"""
    user.avatar = f"""{form_data['avatar']}"""
    user.admin = f"""{form_data['admin']}"""
    user.bio = f"""{form_data['bio']}"""

    db.session.commit()
    if form_data['type'] == "onboarding":
        home = url_for('modpipe.index')
        if current_user.is_authenticated:
            home = url_for('modpipe.dashboard')
        return redirect(f"{home}?welcome")
    return redirect(url_for('auth.edit_user').replace('http://','https://'))

app/templates/base.html
<!doctype html>
<html class="bg-zinc-400 dark:bg-zinc-700">
    <head>
        <title>modPIPE Streamer Dashboard</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="/css/modpipe.css">
        <link rel="shortcut icon" href="/img/favicon.ico">
        <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.css" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@600&display=swap" rel="stylesheet">
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body class="min-h-screen">

        {% include "nav.html" %}

        <main id="content_section" class="min-h-full">

        {% block content %}
        {% endblock %}

        </main>

        {% include "footer.html" %}
        
        <!-- // logic to include modals //-->
        {% if current_user.is_authenticated == True %}
            {% if request.path == "/modpipe/dashboard" %}
                {% include "new_command.html" %}
                {% include "config.html" %}
            {% endif %}
        {% endif %}
        {% if current_user.is_authenticated != True %}
            {% include "login.html" %}
        {% endif %}
        {% if request.args.get('welcome') %}
            {% include "welcome.html" %}
        {% endif %}


        <!-- // Logic to include javascript files // -->
        <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.js"></script>
        {% if current_user.is_authenticated != True %}
        <script src="/js/login.js"></script>
        {% endif %}
        {% if request.args.get('welcome') %}
        <script src="/js/welcome.js"></script>
        {% endif %}
        {% if request.path == "/modpipe/dashboard" %}
        <script src="/js/dashboard.js"></script>
        {% endif %}
        <script src="/js/nav.js"></script>
    </body>
</html>

app/templates/config_full.html
{% extends "base.html" %}

{% block content %}
<section class="bg-white dark:bg-gray-900">
    <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
        <h1 class="mb-1 text-2xl font-bold text-gray-900 dark:text-white">Service Configuration</h1>
        <p class="text-md text-gray-900 dark:text-white mb-6">
            Below are options to link your accounts to our service.  Please read our <a class="font-semibold underline" href="/privacy">Privacy Policy</a> to fully understand what and
            why we collect this information, along with how we can use and safeguard this information.
        </p>
            <!-- NightBot -->
            <form method="post" action="config/nightbot">
            <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                <div class="sm:col-span-2 ml-2 mb-1 text-2xl font-bold text-gray-900 dark:text-white">
                    NightBot
                </div>
            </div>
            <div class="p-4 mb-4 border-solid border-2 rounded-md border-blue-900">
                <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                    <div class="sm:col-span-2">
                        <label for="nightbot_display_name" class="ml-2 block mb-2 text-sm font-medium text-gray-900 dark:text-white">Display Name</label>
                        <input type="text" name="nightbot_display_name" id="nightbot_display_name" placeholder="For Recognition Purposes"
                            value="{{nightbot_data['display_name']}}"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600
                            focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600
                            dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    </div>
                    <div class="w-full">
                        <label for="nightbot_client_id" class="ml-2 block mb-2 text-sm font-medium text-gray-900 dark:text-white">client_id</label>
                        <input type="password" name="nightbot_client_id" id="nightbot_client_id" placeholder="oauth2 client_id" required
                            value="{{nightbot_data['client_id']}}""
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600
                            focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600
                            dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <input type="checkbox" onclick="togglePassword('nightbot_client_id')" class="ml-2 w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <span class="ml-1 pt-2 text-sm font-medium text-gray-900 dark:text-white">Show client_id</span>
                    </div>
                    <div class="w-full">
                        <label for="nightbot_client_secret" class="ml-2 block mb-2 text-sm font-medium text-gray-900 dark:text-white">client_secret</label>
                        <input type="password" name="nightbot_client_secret" id="nightbot_client_secret" placeholder="oauth2 client_secret" required
                            value="{{nightbot_data['client_secret']}}"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <input type="checkbox" onclick="togglePassword('nightbot_client_secret')" class="ml-2 w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <span class="ml-1 pt-2 text-sm font-medium text-gray-900 dark:text-white">Show client_secret</span>
                    </div>
                    <div class="sm:col-span-2 mb-1 text-xl font-bold text-gray-900 dark:text-white text-right">
                        <button type="submit"
                        class="inline-flex items-center px-5 py-2.5
                        text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4
                        focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">Save & Authorize</button>
                    </div>
                </div>
            </div>
            </form>
            <!-- Twitch -->
            <form method="post" action="config/twitch">
            <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                <div class="sm:col-span-2 mx-2 mb-1 text-2xl font-bold text-gray-900 dark:text-white">
                    Twitch
                </div>
            </div>
            <div class="p-4 mb-4 border-solid border-2 rounded-md border-blue-900">
                <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                    <div class="sm:col-span-2">
                        <label for="twitch_display_name" class="ml-2 block mb-2 text-sm font-medium text-gray-900 dark:text-white">Display Name</label>
                        <input type="text" name="twitch_display_name" id="twitch_display_name" placeholder="For Recognition Purposes"
                            value="{{twitch_data['display_name']}}"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600
                            focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600
                            dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                    </div>
                    <div class="w-full">
                        <label for="client_id" class="ml-2 block mb-2 text-sm font-medium text-gray-900 dark:text-white">client_id</label>
                        <input type="password" name="twitch_client_id" id="twitch_client_id" placeholder="oauth2 client_id" required
                            value="{{twitch_data['client_id']}}"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600
                            focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600
                            dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <input type="checkbox" onclick="togglePassword('twitch_client_id')" class="ml-2 w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <span class="ml-1 pt-2 text-sm font-medium text-gray-900 dark:text-white">Show client_id</span>
                    </div>
                    <div class="w-full">
                        <label for="client_secret" class="ml-2 block mb-2 text-sm font-medium text-gray-900 dark:text-white">client_secret</label>
                        <input type="password" name="twitch_client_secret" id="twitch_client_secret" placeholder="oauth2 client_secret" required
                            value="{{twitch_data['client_secret']}}"
                            class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-600 focus:border-blue-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500">
                        <input type="checkbox" onclick="togglePassword('twitch_client_secret')" class="ml-2 w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600">
                        <span class="ml-1 pt-2 text-sm font-medium text-gray-900 dark:text-white">Show client_secret</span>
                    </div>
                    <div class="sm:col-span-2 mb-1 text-xl font-bold text-gray-900 dark:text-white text-right">
                        <button type="submit"
                        class="inline-flex items-center px-5 py-2.5
                        text-sm font-medium text-center text-white bg-blue-700 rounded-lg focus:ring-4
                        focus:ring-blue-200 dark:focus:ring-blue-900 hover:bg-blue-800">Save & Authorize</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
      
  </section>
{% endblock %}

app/templates/dashboard.html
{% extends "base.html" %}

{% block content %}

<!-- Example Dashboard -->

<section class="bg-white dark:bg-gray-900 min-h-screen">
    <div id="dashboard_wrapper" class="py-8 px-4 mx-auto max-w-screen-xl text-center  lg:px-6">
        
        <!-- // CRUD Bar START // -->
        <div class="mx-auto mb-4">
        
            <div class="justify-between items-center pt-0 flex px-10 align-middle">

                <!-- // Left CRUD Controls // -->
                <div class="items-center sm:flex align-middle">
                    <!-- // Configure Button // -->
                    <button class="h-14 inline-flex items-center px-5 py-3 text-sm font-medium text-center
                            text-gray-900 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300
                            fill-gray-900 dark:fill-gray-400
                            border-2 rounded-lg border-gray-500 dark:border-gray-400
                            hover:border-gray-400 hover:dark:border-gray-200"
                            id="edit_commands" type="button"
                            onclick="configModal.show()">Configure</button>
                </div>
                <!-- // Right CRUD Controls // -->
                <div class="items-center sm:flex align-middle">
                    <!-- // New Button // -->
                    <button class="h-14 inline-flex items-center px-5 py-3 ml-4 text-sm font-medium text-center
                            text-gray-900 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300
                            fill-gray-900 dark:fill-gray-400
                            border-2 rounded-lg border-gray-500 dark:border-gray-400
                            hover:border-gray-400 hover:dark:border-gray-200"
                            id="new_command" type="button" onclick="showCommandModal()">New</button>
                </div>
            </div>
        </div>
        <!-- // CRUD Bar END // -->
        
        {% if commands|length < 1 %}
        <div class="w-full p-4 m-4 text-black dark:text-gray-100 text-2xl font-bold min-h-64 flex items-center">
            <p class="w-full text-center">
                It's awfully empty in here.  Try creating a new command!
            </p>
        </div>
        {% endif %}
        <!-- // Command Blocks START //-->
        <div id="dashboard_command_blocks" 
             class="grid gap-4 lg:gap-8 grid-cols-2 md:grid-cols-3 lg:grid-cols-4
             align-middle max-w-2/3 min-w-64 place-items-center">

            {% include 'dashboard/command_blocks.html' %}

        </div>  
    </div>
  </section>

{% endblock %}

app/templates/index.html
<html>
  <head>
    <title>Flask + OAuth 2.0 Demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">Flask + OAuth 2.0 Demo</a>
      </div>
    </nav>
    <div class="container mt-3">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="alert alert-info" role="alert">
          {% for message in messages %}
            {{ message }}<br>
          {% endfor %}
          </div>
        {% endif %}
      {% endwith %}
      {% if current_user.is_authenticated %}
        <h2>Hi, {{ current_user.username }}!</h2>
        <p>
          <a class="btn btn-primary" href="{{ url_for('auth.logout') }}">Logout</a>
        </p>
      {% else %}
        <p>
          <a class="btn btn-primary" href="{{ url_for('auth.oauth2_authorize', provider='google') }}">Login with Google</a>
          <a class="btn btn-primary" href="{{ url_for('auth.oauth2_authorize', provider='github') }}">Login with GitHub</a>
        </p>
      {% endif %}
    </div>
  </body>
</html>

app/templates/login.html
<!-- Login Popup -->
<div id="login-popup" tabindex="-1" class="hidden overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 z-50 w-full md:inset-0 h-modal md:h-full">
    <div class="relative p-4 w-full max-w-lg h-full md:h-auto">
        <div class="relative p-4 bg-white rounded-lg shadow md:p-8 
             dark:bg-gray-800 border-2 rounded-lg border-gray-500 dark:border-gray-400">
            <div class="mb-4 text-sm font-light text-gray-500 dark:text-gray-400">
                <h3 class="mb-3 text-2xl font-bold text-gray-900 dark:text-white">OAuth Login</h3>
                <div class="text-center">
                    <a href="{{ url_for('auth.oauth2_authorize', provider='twitch') }}">
                        <button class="h-12 inline-flex items-center px-5 py-2.5 mt-4 mx-4 sm:mt-6 text-sm font-medium text-center
                                text-gray-900 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300
                                fill-gray-900 dark:fill-gray-400
                                border-2 rounded-lg border-gray-500 dark:border-gray-400
                                hover:border-gray-400 hover:dark:border-gray-200">
                            <svg class="h-7 w-7 fill-inherit" x="0px" y="0px" viewBox="0 0 2400 2800" style="enable-background:new 0 0 2400 2800;">
                                <style type="text/css">.st0{fill:#FFFFFF;}.st1{fill:#9146FF;}</style>
                                <g><polygon class="st0" points="2200,1300 1800,1700 1400,1700 1050,2050 1050,1700 600,1700 600,200 2200,200"/><g><g id="Layer_1-2">
                                <path class="st1" d="M500,0L0,500v1800h600v500l500-500h400l900-900V0H500z M2200,1300l-400,400h-400l-350,350v-350H600V200h1600 V1300z"/>
                                <rect x="1700" y="550" class="st1" width="200" height="600"/>
                                <rect x="1150" y="550" class="st1" width="200" height="600"/></g></g></g>
                            </svg>
                            <span class="pl-4">Login with Twitch</span>
                        </button>
                    </a>

                    <a href="{{ url_for('auth.oauth2_authorize', provider='google') }}">
                        <button class="h-12 inline-flex items-center px-5 py-2.5 mt-4 mx-4 sm:mt-6 text-sm font-medium text-center
                                text-gray-900 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300
                                fill-gray-900 dark:fill-gray-400
                                border-2 rounded-lg border-gray-500 dark:border-gray-400
                                hover:border-gray-400 hover:dark:border-gray-200">
                            <img class="max-h-7 max-w-7" src="/img/google.svg"/> <span class="pl-4">Login with Google</span>
                        </button>
                    </a>

                    <a href="{{ url_for('auth.oauth2_authorize', provider='github') }}">
                        <button class="h-12 inline-flex items-center px-5 py-2.5 mt-4 mx-4 sm:mt-6 text-sm font-medium text-center
                                text-gray-900 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300
                                fill-gray-900 dark:fill-gray-400
                                border-2 rounded-lg border-gray-500 dark:border-gray-400
                                hover:border-gray-400 hover:dark:border-gray-200">
                                <svg class="h-7 w-7 fill-inherit" viewBox="0 0 1024 1024" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0C3.58 0 0 3.58 0 8C0 11.54 2.29 14.53 5.47
                                15.59C5.87 15.66 6.02 15.42 6.02 15.21C6.02 15.02 6.01 14.39 6.01 13.72C4 14.093.48 13.23 3.32
                                12.78C3.23 12.55 2.84 11.84 2.5 11.65C2.22 11.5 1.82 11.13 2.49 11.12C3.12 11.11 3.57 11.7 3.72
                                11.94C4.44 13.15 5.59 12.81 6.05 12.6C6.12 12.08 6.33 11.73 6.56 11.53C4.78 11.33 2.92 10.64 2.92
                                7.58C2.92 6.71 3.23 5.99 3.74 5.43C3.66 5.23 3.38 4.41 3.82 3.31C3.82 3.31 4.49 3.1 6.02 4.13C6.66
                                3.95 7.34 3.86 8.02 3.86C8.7 3.86 9.38 3.95 10.02 4.13C11.55 3.09 12.22 3.31 12.22 3.31C12.66 4.41
                                12.38 5.23 12.3 5.43C12.81 5.99 13.12 6.7 13.12 7.58C13.12 10.65 11.25 11.33 9.47 11.53C9.76 11.78
                                10.01 12.26 10.01 13.01C10.01 14.08 10 14.94 10 15.21C10 15.42 10.15 15.67 10.55 15.59C13.71 14.53
                                16 11.53 16 8C16 3.58 12.42 0 8 0Z" transform="scale(64)"/>
                                </svg>
                                <span class="pl-4">Login with GitHub</span>
                        </button>
                    </a>
                </div>
            </div>
            <div class="justify-between items-center pt-0 space-y-4 sm:flex sm:space-y-0">
                <a href="#" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">What data do we collect?</a>
                <div class="items-center space-y-4 sm:space-x-4 sm:flex sm:space-y-0">
                    <button class="h-12 inline-flex items-center px-5 py-2.5 mt-4 mx-4 sm:mt-6 text-sm font-medium text-center
                            text-gray-900 hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-300
                            fill-gray-900 dark:fill-gray-400
                            border-2 rounded-lg border-gray-500 dark:border-gray-400
                            hover:border-gray-400 hover:dark:border-gray-200"
                            id="close-login" type="button">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/user.html
{% extends "base.html" %}

{% block content %}
    <div class="p-5 self-center justify-center items-center text-slate-800 dark:text-slate-200 text-3xl">
        
        {% for item in current_user.__dict__ %}
        {% if not item.startswith('_') %}
            <p>{{item}}: {{ current_user.__dict__[item] }}</p>
        {% endif %}
        {% endfor %}
        <p><a href="/auth/user/edit">Edit User</a></p>
    </div>
{% endblock %}